spring:
  application:
    name: wechat-mp-helper
---
server:
  address: 127.0.0.1
  port: 8888
---
logging:
  file: /data/logs/wechat-mp-helper/wechat-mp-helper.log
---
spring:
  data:
    mongodb:
      authentication-database: wechat-mp-helper
      database: wechat-mp-helper
      host: 127.0.0.1
      port: 27017
      username: wechat-mp-helper
      password: e484db270b70439b93839c9ff91878ce
