spring:
  application:
    name: wall-e
---
server:
  address: 127.0.0.1
  port: 8888
---
logging:
  file: /data/logs/wall-e/wall-e.log
---
spring:
  data:
    mongodb:
      authentication-database: wall-e
      database: wall-e
      host: 112.74.169.188
      port: 27017
      username: wall-e
      password: c1a0c3e60c9d11e8b9aa00163e02b6ed
